apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-luisatoledo
  namespace: luisatoledo
spec:
  storageClassName: default-storage-class-luisatoledo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: luisatoledo